In [ ]:
import numpy as np

def generate_random_feasible_solution(n):
    return np.random.uniform(-1, 1, size=n)

def is_feasible(solution):
    return np.all(solution >= -1) and np.all(solution <= 1)

def monte_carlo_sampling(num_samples, num_vertices):
    feasible_samples = []
    num_generated = 0
    while len(feasible_samples) < num_samples:
        solution = generate_random_feasible_solution(num_vertices)
        if is_feasible(solution):
            feasible_samples.append(solution)
        num_generated += 1
    return feasible_samples

# Example usage
num_samples = 10
num_vertices = 5
samples = monte_carlo_sampling(num_samples, num_vertices)
print("Generated feasible samples:")
for sample in samples:
    print(sample)

Generated feasible samples:
[-0.00429242 -0.13514543  0.01975583  0.84779233  0.58879336]
[ 0.60417787 -0.57351552  0.38112429 -0.72469659 -0.48415766]
[ 0.80585164 -0.11594102 -0.1575577   0.46629312 -0.08706556]
[-0.5023246   0.9343712  -0.94375562  0.34202055  0.46778829]
[ 0.75017561 -0.19267169  0.30839007 -0.63294636  0.34279077]
[ 0.40309595  0.17657881  0.88765838 -0.95343288 -0.45788313]
[-0.16949255 -0.97539731  0.54275938 -0.16864146 -0.70206819]
[ 0.7776891   0.56684808 -0.64975268 -0.24790106  0.83704811]
[-0.68717635 -0.5180505  -0.80219469 -0.74555778 -0.1736145 ]
[ 0.87499635 -0.22628535  0.91189272  0.07889496 -0.13568342]


In [1]:
import numpy as np
from scipy.io import mmread

# Function to generate a random feasible solution
def generate_random_solution(num_vertices):
    return np.random.uniform(-1, 1, size=num_vertices)

# Function to check if a solution is feasible
def is_feasible(solution):
    return np.all(solution >= -1) and np.all(solution <= 1)

# Load graph from .mtx file
file_path = "/content/MANN-a27.mtx"
graph = mmread(file_path).toarray()

# Number of vertices
num_vertices = len(graph)

# Monte Carlo sampling
num_samples = 10
feasible_samples = []
while len(feasible_samples) < num_samples:
    solution = generate_random_solution(num_vertices)
    if is_feasible(solution):
        feasible_samples.append(solution)

# Print generated feasible samples
for sample in feasible_samples:
    print(sample)


[ 0.73395803 -0.34997781  0.60221957  0.1721454   0.96022861 -0.14993444
 -0.02990787 -0.2084233  -0.18374154 -0.59269418 -0.01388583 -0.90455601
 -0.82293216  0.02066054  0.39627944  0.34468956  0.6629418   0.67020617
  0.2475491   0.67214471 -0.46704638 -0.16365125 -0.63590891  0.46861369
 -0.61462518  0.35214301  0.59793431  0.48423391  0.47547389  0.65073515
 -0.35387745 -0.07504703 -0.216497    0.26203001 -0.04217074  0.9027785
  0.43192211 -0.04558511  0.43216326  0.41704731 -0.4636871  -0.21871972
 -0.2210412  -0.14857198 -0.01120165 -0.77793165  0.75139205 -0.80492551
  0.5574179  -0.33766058 -0.57953991  0.12433676  0.4874299  -0.28959902
 -0.56621837  0.03944984  0.45474738 -0.94189009  0.91995532 -0.31981558
  0.89742601 -0.03429388 -0.82687397 -0.72759478  0.81651671 -0.16648325
 -0.79610581 -0.9182268  -0.72956978  0.32371135  0.74575549 -0.47855734
  0.54884611 -0.36720518 -0.76128873  0.04864948  0.56440041 -0.30151574
 -0.85413452 -0.20190481  0.0514413  -0.79063873 -0.